README.md, front_end/ndb/NdbMain.js, front_end/ndb/module.json
This command will run `node ${script}`, ndb will automatically attach.
=> feat(ui): added "Run this script" to the SourceCode context menu

ndb.js
This flag may produce error at start on some Linux distributions.
At the same time we control what code is executed in browser and
expose some capabilities like way to run node process so
sandboxing is not as usefull as it is inside Chrome.
Fixes #13
=> fix(startup): run pptr with --no-sandbox flag

front_end/ndb/NdbMain.js
=> fix(debugger,win): properly escape \ in paths for blackbox pattern

lib/file_system_backend.js, lib/search_backend.js, ndb.js, services/services.js
When NDB_DEBUG_FRONTEND is set we should route each call to frontend
through setTimeout, otherwise as soon as we pause at breakpoint on
frontend side, all calls will be processed in incorrect order.
=> fix(debug_frontend): improve frontend debugging experience

ndb.js
ndb dumpes version info and short help when run with corresponded
flag.
Fixes #17
=> fix(cli): support --version and --help flags

front_end/ndb/NdbMain.js, front_end/ndb/module.json, front_end/ndb_ui/NodeModulesBlackboxing.js, front_end/ndb_ui/module.json, front_end/ndb_ui/nodeModulesBlackboxing.css
- new tab is added to settings, called 'Node modules',
- user can whitelist some modules there.
User can see whitelisted modules in navigator and debug them in
debugger.
Fixes #45
=> feat(whitelist): add the way to whitelist node_module

front_end/ndb/NdbMain.js, front_end/ndb_ui/NodeModulesBlackboxing.js, lib/file_system_backend.js, lib/launcher.js, lib/search_backend.js, package-lock.json, package.json, scripts/build_release_application.js
fs.watch is replaced by chokidar to avoid mac limitations.
drive-by: faster loading dependencing in node_modules settings.
drive-by: do not look deeper then 2 folders when ndb runs from
folder without package.json.
Fixes #27
=> fix(backend): improve fs watcher

.npmignore, build.js, front_end/ndb/NdbMain.js, lib/launcher.js, package-lock.json, package.json
We can build frontend once and publish it.
Advantages:
- build once, do not do it on each installation,
- we can verify build before publishing.
Fixes #23
=> fix(build): publish prebuilt frontend

node_debug_demon/preload.js
CJS modules can return a result. Currently the `callAndPauseOnStart()` wrapper is not forwarding it along.
=> Forward return value from callAndPauseOnStart() wrapper.

front_end/ndb/NdbMain.js, lib/launcher.js
If we have target file with the same content inside file system we can just clear sourceContent inside sourceMap.
Fixes #34
=> fix(frontend): clear sourcesContent inside sourceMap if redundant

services/terminal.js
If variable is empty or points to not existing file then fallback
to cmd.exe for win and bash for linux and mac.
Fixes #78
=> feat(backend): get shell for terminal for $SHELL variable

package-lock.json, package.json
new frontend includes:
- better BigInt support for format string, e.g., console.log("%d", 1n),
- more reliable and fast CallStackSidebarPane.
=> feat(frontend): roll DevTools frontend to 582044

front_end/ndb/NdbMain.js, lib/file_system_backend.js, lib/launcher.js, ndb-inspect/.gitignore, ndb-inspect/LICENSE, ndb-inspect/README.md, ndb-inspect/brk, ndb-inspect/inspect.js, ndb-inspect/package.json, ndb-inspect/preload.js, scripts/build_release_application.js, services/ndd_service.js, services/terminal.js
ndb-inspect is trivial package, that allow to replace --inspect
and --inspect-brk with -r ndb-inspect and -r ndb-inspect/brk.
=> feat(ndb-inspect): added --inspect like flag for ndb

README.md
* Remove superfluous hyphen in `npm install --g` script
* Remove `--production` flag from `npm install -g`
* Add yarn cmd for local install
* Minor grammar fix
=> docs(README.md): minor fixes to documentation

front_end/ndb/NdbMain.js, front_end/ndb/module.json, front_end/ndb_app.json, front_end/ndb_ui/NodeProcesses.js, front_end/ndb_ui/RunConfiguration.js, front_end/ndb_ui/module.json, package-lock.json, package.json
There are three possible ways to use performance panel:
- run target script with "Pause at start", go to performance panel
and start recording,
- start recording on performance panel, open terminal in drawer
and run any node script from there.
- using "Start recording.." button in NPM scripts sidebar.
As bonus:
- removed "Wait at end" checkbox.
=> feat(perf): add timeline panel

lib/repl.js
console.context does not exist until specific 8.x release.
Use console.log as workaround.
Fixes #136
=> fix(repl): use console.log for old Node 8.x releases

package-lock.json, package.json
1.8.0 supports PUPPETEER_EXECUTABLE_PATH. With this flag user can
install and use ndb using locally installed Chrome. There is no
guarantees that all features would work as expected.
Fixes #134
=> feat(pptr): roll pptr to 1.8.0

front_end/ndb/NdbMain.js, inspect, inspect-brk
To align -r ndb/inspect-brk behavior with --inspect-brk, we should
force pause at start if arguments contain ndb/inspect-brk.
=> fix(ndb/inspect): ndb should pause at start with ndb/inspect-brk

lib/process_utility.js, package-lock.json, services/file_system.js, services/ndd_service.js
- fs.watch is more reliable in case when there is no free space for
new inotify handles, ndd can use it instead of chokidar,
- fs service should be ready for ENOSPC errors.
=> fix(ndd,fs): use fs.watch instead of chokidar in ndd

services/file_system.js
When the path was converted into a file URI, the length wasn't updated
to reflect the percent-encoded sequences (e.g.: %20).
It fixes:
https://github.com/GoogleChromeLabs/ndb/issues/221
This is my first pull request, so I hope I'm getting everything right!
=> fix(services/file_system): correct path length parsing

lib/launcher.js
For internal errors the message alone is not very helpful. For example I got net::ERR_NAME_NOT_RESOLVED at <url>,
but I have no idea where this came from or why. With the call stack I can see the issue is in FrameManager.navigate().
=> Log the stack for unhandledRejections

front_end/ndb/NdbMain.js, lib/backend.js
=> adjust source maps to account for node script wrapping

front_end/ndb/NdbMain.js
targetManager.removeTarget does not dispose target by default.
=> fix(frontend): dispose target after disconnect

README.md, front_end/ndb/NdbMain.js, front_end/ndb_ui/RunConfiguration.js
User can click record button next to configuration on bottom left
side of the sources panel. This button start profiler for given
process and run it as long as process is allive.
User can add --prof flag to ndb to profile entire app run,
e.g. ndb --prof npm run unit
Ctrl/Cmd + R restarts last profiling.
=> feat(profiler): auto stop profiler when app is finished

front_end/ndb/InspectorFrontendHostOverrides.js, lib/backend.js
All urls in ndb are file urls, host method should be able to load file.
Fixes https://github.com/GoogleChromeLabs/ndb/issues/232
=> fix(frontend): InspectorFrontendHost.loadNetworkResource override

front_end/ndb/NdbMain.js
In 1.0.49 more radical behavior was introduced - do not connect
to all process with blackboxed main or with main outside cwd.
Fixes https://github.com/GoogleChromeLabs/ndb/issues/269
=> fix(frontend): do not connect iff main is blackboxed

.npmignore
1.0.51 was published with 1.0.50.tgz pkg inside. :(
=> chore(npmignore): added *.tgz to avoid publishing packed package

front_end/ndb/NdbMain.js, front_end/ndb_ui/NodeProcesses.js, lib/preload/ndb/preload.js, services/ndd_service.js
Node 8 can not process any command before `Runtime.runIfWaitingForDebugger` so preload should fetch all required information by itself and send it to frontend using file.
It allows to simplify some parts of frontend  - we do not need to listen for target name changes any more - it never changes.
drive-by: we do not need to fetch web socket url from http endpoint for Node 10 and Node 12.
=> fix(node8): fixed node 8 support

front_end/ndb.json, front_end/ndb/NdbMain.js, front_end/ndb/module.json, front_end/ndb_sdk/NodeRuntime.js, front_end/ndb_sdk/NodeWorker.js, front_end/ndb_sdk/module.json, lib/preload/ndb/preload.js, services/ndd_service.js
It is full support: debugging and profiling works with Node 12.
Fixes https://github.com/GoogleChromeLabs/ndb/issues/277
=> feat(frontend): added node worker support

front_end/ndb/NdbMain.js, front_end/ndb_ui/NodeProcesses.js
node reports scripts with wrapper, source maps are generated without
wrapper, we need to adjust first line mappings in source map.
drive-by: fix 'paused' state of node process.
=> fix(sourcemap): only first line mappings should be adjusted

front_end/ndb/NdbMain.js, front_end/ndb_ui/Terminal.js, lib/backend.js, services/ndd_service.js, services/terminal.js
carlo spawns child processes with detach flag. We should route
terminal data through frontend to show it in main process stdout.
The big bug: https://github.com/GoogleChromeLabs/ndb/issues/204
drive-by: fixed https://github.com/GoogleChromeLabs/ndb/issues/168
=> fix(ndd): ndd service should not use process.stdout

lib/preload/ndb/preload.js, package.json, services/ndd_service.js, services/terminal.js, version.js
As less environment variable we pass around as easier it to run
a little script to allow external node instances to connect to ndb.
drive-by: inspector.open to start inspector instead of passing
--inspect flag.
=> refactor(backend): inline NDB_VERSION

front_end/ndb/NdbMain.js, front_end/ndb_ui/RunConfiguration.js
Sometimes windows can not resolve path to npm, full path should be
more reliable.
Partially fixes https://github.com/GoogleChromeLabs/ndb/issues/164
=> fix(frontend): substitute node and npm with full paths

services/file_system.js
Starting with v10, Node uses file urls in inspector protocol.
Breakpoints work iff file path is reported using file url.
Otherwise provisional breakpoint will use path with spaces,
instead of %20.
Bug: https://github.com/GoogleChromeLabs/ndb/issues/204
=> fix(backend): report file urls for file system

front_end/ndb/FileSystem.js, front_end/ndb/NdbMain.js, lib/backend.js, lib/filepath_to_url.js, lib/launcher.js, lib/preload/ndb/preload.js, services/file_system.js, services/ndd_service.js, services/search.js
FileSystem works only with file urls.
All breakpoints are set by path and by url.
Frontend gets only file urls from ndb backend and passes only file
urls to backend. There is only one exception - 'Run this script'
frontend action convert script file url to path on frontend side.
Over the protocol any url is always returned as file urls (frontend
patches messages from Node 8). Debugger.setBreakpointByUrl replaces
url with regex pattern: path|url to work with Node 8 and later Nodes.
https://github.com/GoogleChromeLabs/ndb/issues/204
=> fix(frontend): frontend uses file urls instead of paths

front_end/ndb/FileSystem.js
Image should be reported using base64 encoding.
=> fix(frontend): report image file content as base64
