- front_end/ndb/NdbMain.js
- front_end/ndb_ui/NodeProcesses.js
- front_end/ndb_ui/Terminal.js
- ndb.js
> feat(ui): add repl for console

- ndb.js
> fix(ui,mac): maximizing should not freeze ndb

- ndb.js
- node_debug_demon/client.js
- services/ndd_service.js
- services/npm_service.js
- services/services.js
> fix(shutdown): kill running nodes during shutdown

- front_end/ndb/NdbMain.js
- services/ndd_service.js
> fix(win): ndb should work with spaces inside paths

- scripts/build_release_application.js
> fix(build): more reliable build

- front_end/ndb/NdbMain.js
- lib/launcher.js
+ minor NDB_DEBUG_FRONTEND fix
Fixes #50
> fix(console): fix welcome msg color with light theme

- front_end/ndb/NdbMain.js
- lib/file_system_backend.js
- lib/launcher.js
Source map should just work with basic tsc workflow.
Fixes #57
> fix(frontend): radically improve source map support

- front_end/integration_test_runner.json
- front_end/ndb/NdbMain.js
- front_end/ndb_ui/RunConfiguration.js
- front_end/sources_test_runner/module.json
- front_end/test_runner/TestRunner.js
- lib/launcher.js
- ndb.js
- test/assets/test-project/index.mjs
- test/assets/test-project/package.json
- test/basic.spec.js
drive-by: introduce new test based on puppeteer and DevTools helpers.
Fixes #67
> fix(debugger): breakpoints should work with experimental modules

- .npmignore
- build.js
- front_end/ndb/NdbMain.js
- front_end/ndb/module.json
- lib/launcher.js
- node_debug_demon/preload.js
- package-lock.json
- package.json
- services/ndd_service.js
>  fix(frontend): exclude .git by default 

- README.md
- mentioned local installation option
- added link with different advices about resolving permission errors.
> fix(doc): local installation option

- ndb.js
Message like npm i -g ndb better fits ndb needs.
> fix(backend): pass isGlobal:true to update-notifier

- front_end/ndb/NdbMain.js
- package-lock.json
- package.json
- services/ndd_service.js
- services/services.js
- added throttler for sending notification from service,
- used raw Runtime.evaluate and Runtime.addBinding instead of exposeFunction,
Solution on top of raw protocol is faster then current exposeFunction
and at the same time we need to send all messages from service to frontend
using the same channel to simplify throtling logic.
> fix(backend): use internal pptr channel as service - fe channel

- front_end/ndb/FileSystemMapping.js
> fix(frontend): rawLocation may return empty script

- lib/file_system_backend.js
- package-lock.json
- package.json
- latest DevTools frontend contains automapping fix,
- backend fs fix fetching content of small files.
Helps with #95
> fix(frontend,backend): roll devtools frontend and fix file reading

- lib/file_system_backend.js
Backend should be ready for this.
> fix(backend): stream.read() may return null

- build.js
- package-lock.json
- package.json
- scripts/build_release_application.js
These workerse are required for heap_snapshot and for formatting.
Fixes #116
> fix(build): include worker apps to prebuilt .local-frontend

- package-lock.json
- package.json
This roll includes live expression and preparation for performance
panel.
> feat(frontend): roll DevTools frontend to 589976

- lib/launcher.js
- package-lock.json
- package.json
Unfrotunately 1.6.x has canvas rendering issue that blocks timeline.
> feat(pptr): roll to 1.7.0

- front_end/host/InspectorFrontendHostOverrides.js
- lib/launcher.js
> fix(frontend): implemented InspectorFrontendHost.bringToFront

- front_end/ndb/NdbMain.js
- package-lock.json
- package.json
This roll includes preparation for file urls in protocol.
> feat(frontend): roll frontend to 592326

- package-lock.json
- package.json
Unfortunately Chromium on Mac is broken:
- checkboxes are blinking,
- scrollbars are red.
> Revert "feat(pptr): roll pptr to 1.8.0 (#147)"

- .eslintrc.js
- front_end/ndb/FileSystem.js
- front_end/ndb/NdbMain.js
- front_end/ndb/module.json
- front_end/ndb_ui/NodeProcesses.js
- front_end/ndb_ui/RunConfiguration.js
- front_end/ndb_ui/Terminal.js
- package-lock.json
- package.json
- services/ndd_service.js
- test/basic.spec.js
New DevTools frontend does not allow to specify connection factory
any more so we need to do something else.
> feat(frontend): support for flatten protocol

- services/ndd_service.js
> fix(ndd): undefined += '42' === undefined42

- lib/launcher.js
- lib/process_utility.js
- services/file_system.js
- services/inspector_frontend_host.js
- services/ndd_service.js
- services/ping.js
- services/search.js
- services/terminal.js
It should help to debug cases with stuck processes.
> feat(backend): added ndb/<name> title for each ndb process

- front_end/ndb/NdbMain.js
- package-lock.json
Otherwise not all breakpoints will be restored properly.
> fix(frontend): we should wait for filesystem before run script

- front_end/ndb/NdbMain.js
- package.json
- test/platform.spec.js
- removed unused frontend code,
- fixed blackboxing setting,
- updated carlo version in package.json.
> fix(frontend): minor fixes

- package-lock.json
- package.json
> feat(frontend): roll frontend to 619856

- front_end/ndb_ui/Terminal.js
- package-lock.json
- package.json
- current xterm version contains vulnerability, updated to fix,
- implemented copy/paste context menu.
Fixes #160
> feat(terminal): updated xterm, implemented context menu

- front_end/ndb/NdbMain.js
- lib/launcher.js
- package-lock.json
- package.json
- scripts/build_release_application.js
- at least it should prepare ndb for shadow dom V0 removal,
Fixes #235
Fixes #242
> feat(frontend): roll DevTools frontend to 640176

- front_end/ndb/FileSystem.js
- package-lock.json
- package.json
- services/file_system.js
- services/file_system_io.js
- chokidar 3.0 is much faster and uses less memory,
- fs IO should be separate service to avoid potential blocking by file tree traversal service.
> fix(fs): updated chokidar and split fs service

- .travis.yml
- README.md
- front_end/ndb_ui/Terminal.js
- package.json
npm run test runs only linter.
> chore(build): added basic travis CI

- build.js
- front_end/ndb.json
- front_end/ndb_ui/Terminal.js
- front_end/ndb_ui/module.json
- front_end/xterm/module.json
- lib/launcher.js
- package-lock.json
- package.json
- scripts/builder.js
- services/terminal.js
- thedebugger uses node-pty instead of proxy package,
- any node_module exposed to front_end should be located inside
separate front_end module, e.g. xterm.
> fix(terminal): fixed terminal for Node 12 and Node 10

- package-lock.json
- package.json
Fixes https://github.com/GoogleChromeLabs/ndb/issues/225
> fix(carlo): roll carlo to 0.9.46

- front_end/ndb/NdbMain.js
ndb disconnects from process if main script is outside of cwd or it is blackboxed.
Fixes https://github.com/GoogleChromeLabs/ndb/issues/161
> feat(processes): do not connect if main is blackboxed or outside cwd

- front_end/ndb/FileSystem.js
- front_end/ndb/NdbMain.js
- services/file_system.js
With latest changes it is more important to load main script's
UISourceCode on time. This patch forces loading of main script
ahead of time.
> fix(frontend): fixed addFileSystem race

- lib/backend.js
ndb uses copy of this method from `class Backend`
> fix(backend): removed loadSourceMap duplicate

- front_end/ndb/Connection.js
- front_end/ndb/NdbMain.js
- front_end/ndb/module.json
- services/ndd_service.js
Connection looks more suitable than session router in node use case.
> refactor(connection): use connection instead of router

- package-lock.json
- package.json
The main goal is to update lodash to at least 4.17.13.
> fix(deps): rolled dependency
